# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_pb=_b('\n\x10helloworld.proto\x12\nhelloworld\"\x1a\n\x0bHelloServer\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1a\n\x0bHelloClient\x12\x0b\n\x03msg\x18\x01 \x01(\t2I\n\x07Greeter\x12>\n\x08SayHello\x12\x17.helloworld.HelloServer\x1a\x17.helloworld.HelloClient\"\x00\x42 \n\x0bthispackageB\x0fHelloWorldProtoP\x01\x62\x06proto3')
)




_HELLOSERVER = _descriptor.Descriptor(
  name='HelloServer',
  full_name='helloworld.HelloServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='helloworld.HelloServer.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=58,
)


_HELLOCLIENT = _descriptor.Descriptor(
  name='HelloClient',
  full_name='helloworld.HelloClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='helloworld.HelloClient.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['HelloServer'] = _HELLOSERVER
DESCRIPTOR.message_types_by_name['HelloClient'] = _HELLOCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloServer = _reflection.GeneratedProtocolMessageType('HelloServer', (_message.Message,), dict(
  DESCRIPTOR = _HELLOSERVER,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloServer)
  ))
_sym_db.RegisterMessage(HelloServer)

HelloClient = _reflection.GeneratedProtocolMessageType('HelloClient', (_message.Message,), dict(
  DESCRIPTOR = _HELLOCLIENT,
  __module__ = 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HelloClient)
  ))
_sym_db.RegisterMessage(HelloClient)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013thispackageB\017HelloWorldProtoP\001'))

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=88,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='helloworld.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOSERVER,
    output_type=_HELLOCLIENT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
